# This file contains settings specific to the 'story' theme.

# -- Main Settings -------------------------------------------------
# These settings control the core elements of the theme.

# Website favicon
favicon: /images/favicon.png

# Website logo (Designer Delivered Original Colored Logo)
logo: /images/logo/yuanse_wanzheng_transparent.png

# Main navigation menu
# The landing page will be the root.
nav_menu:
  Home: /
  Philosophy: /philosophy/
  Services: /services/
  Testimonials: /testimonials/

social:
  rednote: https://xxx

footer:
  copyright: '&copy; 2026 Lingxi Weddings and Events Limited'
  social:
    - icon: envelope
      label: Email
      url: "#email"
      class: email-link
      email: contact@elainxi.events
      style: solid
    - icon: instagram
      label: Instagram
      url: https://www.instagram.com/elainxievents/
    - icon: xiaohongshu
      label: "小红书 (ID: elainxievents)"
      url: "https://www.rednote.com/user/profile/67437bc8000000001d02e19a?xsec_token=ABLyBKq3EYacgRGCFTaM1gOCq6osJYt9WhkETzRLsPF1g%3D&xsec_source=pc_search"
    - icon: weixin
      label: "微信 (ID: elainxievents)"
      url: "#wechat"
      class: wechat-link
      wechat: elainxievents

attribution:
  enable: true
  text: "Design: STORY by"
  url: "https://html5up.net"
  name: "HTML5 UP"
